### ISSUE TITLE
Implement custom download URLs

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/resilience-academy-geonode#4]
### Background
In GN 3 we could force the "Original Dataset" Link with a custom URL. That was reflected inside the Download "Original Dataset" link, which was deprecated in GN 4.

As an example, [this layer from RA](https://geonode.resilienceacademy.ac.tz/layers/UAV_LiDAR_Msimbazi-River_DEM_1.00m_4LASERS_v20190310:geonode:UAV_LiDAR_Msimbazi-River_DEM_1.00m_4LASERS_v20190310) has the link overridden:

![image](https://user-images.githubusercontent.com/571129/223443193-3bbaa5d4-5e62-462e-9b1e-db7de7df29fb.png)

making the Original Dataset reference the external link:

![image](https://user-images.githubusercontent.com/571129/223443590-f21d0aae-c111-471d-8412-8c305120ebe9.png)

### Requirement
We need to reproduce this functionality in GN4 to support the custom URLs in RA, and possibly be available with the upgrade to GN 4 without having to migrate the existing custom URLs.

### Solution
The easy way is to check for the existence of such a link (`Link.objects.filter(resource=resource,link_type='original')`) inside the [Dataset.download_url](https://github.com/GeoNode/geonode/blob/master/geonode/layers/models.py#L309) and the [Document.download_url](download_url) properties.

**IMPORTANT**: These URLs will neither be protected nor proxied by GeoNode.

**Comment by marthamareal** [comment]
@giohappy we do not have `original` link_types for documents, should we apply this only for datasets?

**Comment by giohappy** [comment]
>@giohappy we do not have original link_types for documents, should we apply this only for datasets?
what do you mean? Links don't look tied to resource types, and the enumerations for the link types are under the base module.

**Comment by marthamareal** [comment]
Yes @giohappy Links relate to resourcebase, however currently, the original link type is call on only datasets. or in methods that deal with datasets.

**Comment by giohappy** [comment]
Done with https://github.com/geosolutions-it/resilience-academy-geonode/issues/10.
@marthamareal please test the functionality with the RA project.

**Comment by marthamareal** [comment]
@giohappy I have tested the current resilience4 branch with the following.
- Install project with 4.0.x
- Test dataset and document upload
- Customize the original type links and use external links 
- Download and confirm that an external resource is downloaded.
The above steps are passing locally.
