### ISSUE TITLE
Fix renaming of project in GN 4 project

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/resilience-academy-geonode#9]
@marthamareal the renaming of the project from `resilienceacademy` to `resilience_academy_geonode` will complicate the upgrade operations, mainly because it also configured a different DB name.
Please rename all the `resilience_academy_geonode` references into `resilienceacademy`

**Comment by giohappy** [comment]
@marthamareal did you test the project locally, after the renaming and the upgrade to 4.0.x?

**Comment by marthamareal** [comment]
@giohappy I ran the the project after renaming and it was success, however i did not browse the pages and functionality.
